sealingRules:
  - fileRegex: \.dev\.yaml$
    name: mysecret
    namespace: default
    secretsRegex: (password|pin)$
    maxAge: 720h
    cert: 
      path: cert.pem
  - fileRegex: \.prod\.yaml$
    name: mysecret
    namespace: default
    secretsRegex: (password|pin)$
    maxAge: 720h
    cert: 
      path: cert.pem