sealingRules:
  - fileRegex: \.dev\.yaml$
    name: secret
    namespace: default
    secretsRegex: (password|pin)$
    cert:
        maxAge: 720h0m0s
        sources:
            kubernetes:
              context: docker-desktop
              namespace: kube-system
              name: sealit-sealed-secrets