apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
  labels:
    {{- include "sample-chart.labels" . | nindent 4 }}
#  annotations:
#    "sealedsecrets.bitnami.com/cluster-wide": "true"
#    "sealedsecrets.bitnami.com/namespace-wide": "true"
spec:
  encryptedData:
    PASSWORD: {{ .Values.env.password | trimPrefix "ENC:" }}