apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- if (ne "" .Values.sealit.name) }}
  name: {{ .Values.sealit.name }}
  {{- end }}
  {{- if (ne "" .Values.sealit.namespace) }}
  name: {{ .Values.sealit.namespace }}
  {{- end }}
  labels:
    {{- include "sample-chart.labels" . | nindent 4 }}
{{- if and (ne "" .Values.sealit.namespace) (ne "" .Values.sealit.name) }}
  annotations:
  {{- if (eq "" .Values.sealit.namespace) }}
    "sealedsecrets.bitnami.com/cluster-wide": "true"
  {{- else if (eq "" .Values.sealit.name) }}
    "sealedsecrets.bitnami.com/namespace-wide": "true"
  {{- end }}
{{- end }}
spec:
  encryptedData:
    # Here you list your env variables. Do not forget to trim the prefixed "ENC:"!
    #PASSWORD: {{ .Values.env.password | trimPrefix "ENC:" }}
